import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import esbuild from "esbuild";

const arguments_ = process.argv.slice(2);
if (arguments_.some((argument) => argument !== "--check") || arguments_.length > 1) {
  throw new Error(`build: unsupported arguments: ${arguments_.join(" ")}`);
}

const checkOnly = arguments_[0] === "--check";
const packageRoot = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(packageRoot, "../..");
const sourceRoot = path.join(packageRoot, "src");
const html = await readFile(path.join(sourceRoot, "index.html"), "utf8");
const css = await readFile(path.join(sourceRoot, "styles.css"), "utf8");

async function bundle(entryPoint) {
  const result = await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    format: "esm",
    minify: true,
    write: false,
    target: ["es2022"],
    platform: "browser",
  });
  return result.outputFiles[0].text;
}

const mcpScript = await bundle(path.join(sourceRoot, "entries", "mcp.ts"));
const vscodeScript = await bundle(path.join(sourceRoot, "entries", "vscode.ts"));
const composed = html.replace("/*__STYLES__*/", () => css).replace("/*__SCRIPT__*/", () => mcpScript);

if (/<script\s+[^>]*src\s*=/.test(composed)) {
  throw new Error("build: MCP UI bundle must not contain an external <script src>");
}
if (composed.match(/data-ragnarok-graph-app/g)?.length !== 1) {
  throw new Error("build: MCP UI bundle must contain exactly one graph app shell");
}
if (!composed.includes("ontoolresult")) {
  throw new Error("build: MCP UI bundle must wire ontoolresult");
}
if (vscodeScript.includes("ontoolresult") || vscodeScript.includes("ui/initialize")) {
  throw new Error("build: VS Code UI bundle must not contain MCP Apps lifecycle markers");
}
for (const marker of ["graphDocument", "ready", "refresh"]) {
  if (!vscodeScript.includes(marker)) {
    throw new Error(`build: VS Code UI bundle must contain ${marker}`);
  }
}
for (const requiredId of ["loading", "error", "status", "graph-refresh"]) {
  if (!composed.includes(`id="${requiredId}"`)) {
    throw new Error(`build: MCP UI bundle must contain #${requiredId}`);
  }
}

const outputs = new Map([
  [
    path.join(repositoryRoot, "packages", "mcp-server", "src", "ui", "graphAppBundle.ts"),
    "// AUTO-GENERATED by packages/graph-ui/build.mjs - do not edit by hand.\n" +
      "// prettier-ignore\n" +
      `export const GRAPH_APP_HTML = ${JSON.stringify(composed)};\n`,
  ],
  [path.join(repositoryRoot, "media", "memoryGraph.js"), vscodeScript],
  [path.join(repositoryRoot, "media", "memoryGraph.css"), css],
]);

for (const [outputPath, expected] of outputs) {
  if (checkOnly) {
    let current = "";
    try {
      current = await readFile(outputPath, "utf8");
    } catch (error) {
      if (error?.code !== "ENOENT") {
        throw error;
      }
    }
    if (current !== expected) {
      throw new Error(`build: ${path.relative(repositoryRoot, outputPath)} is out of date; run graph-ui build`);
    }
  } else {
    await writeFile(outputPath, expected, "utf8");
  }
}
