/**
 * Generates a human-readable memories.md file from current memory state.
 * Auto-regenerated on every store/forget operation.
 */

import { MemoryEntry, MemoryEntity, MemoryRelationship, MemoryStats } from "./types";

export class MemoryMarkdownExporter {
  generate(params: {
    workspaceEntries: MemoryEntry[];
    workspaceEntities: MemoryEntity[];
    workspaceRelationships: MemoryRelationship[];
    branchEntries: Map<string, MemoryEntry[]>;
    branchEntities: Map<string, MemoryEntity[]>;
    branchRelationships: Map<string, MemoryRelationship[]>;
    stats: MemoryStats;
  }): string {
    const lines: string[] = [];

    lines.push("# Project Memories");
    lines.push("");
    lines.push("> Auto-generated by RAGnarōk Memory Module. Do not edit manually.");
    lines.push(`> Last updated: ${new Date().toISOString()}`);
    lines.push("");

    // Summary
    lines.push("## Summary");
    lines.push("");
    lines.push(`- **Total memories**: ${params.stats.totalMemories}`);
    lines.push(`- **Workspace memories**: ${params.stats.byScope.workspace}`);
    lines.push(
      `- **Branch memories**: ${params.stats.byScope.branch} (across ${params.stats.branches.length} branches)`,
    );
    lines.push(`- **Entities**: ${params.stats.totalEntities}`);
    lines.push(`- **Relationships**: ${params.stats.totalRelationships}`);
    lines.push("");
    lines.push("---");
    lines.push("");

    // Workspace section
    lines.push("## Workspace Memories");
    lines.push("");

    if (params.workspaceEntities.length > 0) {
      lines.push("### Entities");
      lines.push("");
      lines.push("| Entity | Type | Description | Strength |");
      lines.push("|--------|------|-------------|----------|");
      for (const entity of this.sortByStrength(params.workspaceEntities)) {
        lines.push(
          `| ${entity.name} | ${entity.type} | ${this.truncate(entity.description, 60)} | ${entity.strength.toFixed(1)} |`,
        );
      }
      lines.push("");
    }

    if (params.workspaceRelationships.length > 0) {
      lines.push("### Key Relationships");
      lines.push("");
      for (const rel of params.workspaceRelationships.slice(0, 20)) {
        const srcEntity = params.workspaceEntities.find((e) => e.id === rel.sourceId);
        const tgtEntity = params.workspaceEntities.find((e) => e.id === rel.targetId);
        const srcName = srcEntity?.name ?? rel.sourceId;
        const tgtName = tgtEntity?.name ?? rel.targetId;
        lines.push(`- **${srcName}** → ${rel.type} → **${tgtName}** (${this.truncate(rel.description, 40)})`);
      }
      lines.push("");
    }

    if (params.workspaceEntries.length > 0) {
      lines.push("### Recent Memories");
      lines.push("");
      const sorted = this.sortByDate(params.workspaceEntries).slice(0, 20);
      for (let i = 0; i < sorted.length; i++) {
        const entry = sorted[i];
        const date = new Date(entry.createdAt).toISOString().split("T")[0];
        lines.push(`${i + 1}. "${this.truncate(entry.content, 80)}" (${date})`);
      }
      lines.push("");
    }

    // Branch sections
    for (const [branch, entries] of params.branchEntries) {
      lines.push("---");
      lines.push("");
      lines.push(`## Branch: ${branch}`);
      lines.push("");

      const entities = params.branchEntities.get(branch) ?? [];
      const relationships = params.branchRelationships.get(branch) ?? [];

      if (entities.length > 0) {
        lines.push("### Entities");
        lines.push("");
        lines.push("| Entity | Type | Description | Strength |");
        lines.push("|--------|------|-------------|----------|");
        for (const entity of this.sortByStrength(entities)) {
          lines.push(
            `| ${entity.name} | ${entity.type} | ${this.truncate(entity.description, 60)} | ${entity.strength.toFixed(1)} |`,
          );
        }
        lines.push("");
      }

      if (relationships.length > 0) {
        lines.push("### Key Relationships");
        lines.push("");
        for (const rel of relationships.slice(0, 10)) {
          const srcEntity = entities.find((e) => e.id === rel.sourceId);
          const tgtEntity = entities.find((e) => e.id === rel.targetId);
          const srcName = srcEntity?.name ?? rel.sourceId;
          const tgtName = tgtEntity?.name ?? rel.targetId;
          lines.push(`- **${srcName}** → ${rel.type} → **${tgtName}**`);
        }
        lines.push("");
      }

      if (entries.length > 0) {
        lines.push("### Recent Memories");
        lines.push("");
        const sorted = this.sortByDate(entries).slice(0, 10);
        for (let i = 0; i < sorted.length; i++) {
          const entry = sorted[i];
          const date = new Date(entry.createdAt).toISOString().split("T")[0];
          lines.push(`${i + 1}. "${this.truncate(entry.content, 80)}" (${date})`);
        }
        lines.push("");
      }
    }

    return lines.join("\n");
  }

  private sortByStrength(entities: MemoryEntity[]): MemoryEntity[] {
    return [...entities].sort((a, b) => b.strength - a.strength);
  }

  private sortByDate(entries: MemoryEntry[]): MemoryEntry[] {
    return [...entries].sort((a, b) => b.createdAt - a.createdAt);
  }

  private truncate(text: string, maxLen: number): string {
    if (text.length <= maxLen) {
      return text;
    }
    return text.slice(0, maxLen - 3) + "...";
  }
}
