/**
 * Query Planner Agent - Decomposes complex queries into sub-queries
 * Uses LangChain StructuredOutputParser with Zod schemas
 *
 * Architecture: LLM-powered query analysis and decomposition
 */

import { z } from "zod";
import { ILLMProvider } from "../interfaces";
import { Logger } from "../logger";
import { RetrievalStrategy } from "../utils/types";
import { extractKeywords, QUERY_INTENT_WORDS } from "../utils/keywords";

/** Default timeout for LLM requests in milliseconds */
const LLM_TIMEOUT_MS = 15_000;

/** Internal planner tuning knobs — not exposed in QueryPlannerOptions */
const PLANNER_DEFAULTS = {
  maxSubQueries: 5,
  minTopK: 1,
} as const;

// Zod schema for query plan
const SubQuerySchema = z.object({
  query: z.string().describe("The sub-query to search for"),
  reasoning: z.string().describe("Why this sub-query is needed"),
  topK: z.number().optional().describe("Number of results for this sub-query"),
});

const QueryPlanSchema = z.object({
  originalQuery: z.string().describe("The original user query"),
  complexity: z.enum(["simple", "moderate", "complex"]).describe("Query complexity"),
  subQueries: z.array(SubQuerySchema).describe("Decomposed sub-queries"),
  explanation: z.string().describe("Brief explanation of the search strategy"),
  /** Set to true when the plan was generated by heuristic fallback (LLM unavailable) */
  _heuristicFallback: z.boolean().optional(),
});

export type SubQuery = z.infer<typeof SubQuerySchema>;
export type QueryPlan = z.infer<typeof QueryPlanSchema>;

export interface QueryPlannerOptions {
  topicName: string;
  workspaceContext: string;
  topK: number;
  modelFamily: string;
  signal?: AbortSignal;
  retrievalStrategy: RetrievalStrategy;
}

/**
 * Query Planner Agent using Zod for validation
 */
export class QueryPlannerAgent {
  private logger: Logger;
  private planCache = new Map<string, { plan: QueryPlan; timestamp: number }>();
  private static readonly CACHE_TTL_MS = 60_000; // 1 minute
  private static readonly MAX_CACHE_SIZE = 50;

  constructor(private llmProvider: ILLMProvider) {
    this.logger = new Logger("QueryPlannerAgent");
    this.logger.info("QueryPlannerAgent initialized");
  }

  /** Build a cache key from query + relevant options */
  private buildCacheKey(query: string, options: QueryPlannerOptions): string {
    return JSON.stringify({
      q: query,
      modelFamily: options.modelFamily,
      topK: options.topK,
      topicName: options.topicName,
      workspaceContext: options.workspaceContext,
      retrievalStrategy: options.retrievalStrategy,
    });
  }

  /** Determine whether a query can benefit from LLM refinement. */
  public async canRefineWithLLM(query: string): Promise<boolean> {
    const trimmed = query.trim();
    if (trimmed.length === 0 || !trimmed.includes(" ")) {
      return false;
    }

    return this.llmProvider.isAvailable();
  }

  /** Return a cached plan if still valid, promoting it for LRU eviction */
  private getCachedPlan(key: string): QueryPlan | undefined {
    const entry = this.planCache.get(key);
    if (entry && Date.now() - entry.timestamp < QueryPlannerAgent.CACHE_TTL_MS) {
      // Move to end of Map iteration order (most-recently-used)
      this.planCache.delete(key);
      this.planCache.set(key, entry);
      this.logger.debug("Returning cached query plan");
      return entry.plan;
    }
    if (entry) {
      this.planCache.delete(key);
    }
    return undefined;
  }

  /** Store a plan in the cache, evicting oldest if at capacity */
  private cachePlan(key: string, plan: QueryPlan): void {
    if (this.planCache.size >= QueryPlannerAgent.MAX_CACHE_SIZE) {
      const oldest = this.planCache.keys().next().value;
      if (oldest !== undefined) {
        this.planCache.delete(oldest);
      }
    }
    this.planCache.set(key, { plan, timestamp: Date.now() });
  }

  /** Clear the plan cache */
  public clearCache(): void {
    this.planCache.clear();
  }

  /**
   * Convert all sub-queries in a plan to keyword form for BM25-based retrieval.
   * Preserves the original sentence in the reasoning field.
   */
  private convertPlanToKeywords(plan: QueryPlan): QueryPlan {
    return {
      ...plan,
      subQueries: plan.subQueries.map((sq) => {
        const keywordQuery = extractKeywords(sq.query, {
          extraStopWords: QUERY_INTENT_WORDS,
          sanitizeRegex: /[?!.,;:'"()[\]{}]/g,
          minLength: 2,
          deduplicate: false,
        }).join(" ");
        if (keywordQuery === sq.query) {
          return sq;
        }
        return {
          ...sq,
          query: keywordQuery,
          reasoning: `${sq.reasoning} (keyword-adapted from: "${sq.query}")`,
        };
      }),
    };
  }

  /**
   * Build context string from options
   */
  private buildContextString(options: QueryPlannerOptions): string {
    const parts: string[] = [];

    if (options.topicName) {
      parts.push(`Topic: ${JSON.stringify(options.topicName)}`);
    }
    if (options.workspaceContext) {
      parts.push(`Workspace context: ${JSON.stringify(options.workspaceContext)}`);
    }
    if (parts.length === 0) {
      return "No additional context provided.";
    }
    return parts.join("\n");
  }

  /**
   * Build a refinement prompt that includes the heuristic plan for LLM to improve
   */
  private buildRefinementPrompt(
    query: string,
    context: string,
    heuristicPlan: QueryPlan,
    retrievalStrategy?: RetrievalStrategy,
  ): string {
    const heuristicJSON = JSON.stringify(heuristicPlan, null, 2);

    const keywordGuidance =
      retrievalStrategy === RetrievalStrategy.BM25
        ? `
IMPORTANT — Keyword-Based Retrieval Mode:
The retrieval strategy is "${retrievalStrategy}" which uses BM25 keyword matching.
Sub-queries MUST be keyword phrases containing ONLY domain-specific content words.
Remove ALL of these:
- Question/intent words: what, how, why, explain, define, meaning, describe, list, show
- Articles/prepositions: the, a, an, of, in, for, with, at, by, from, to
- Common verbs: is, are, was, were, do, does, have, has, can, will

Examples:
- "What does patronus mean?" -> "patronus"
- "What are the main personality traits of Harry Potter?" -> "Harry Potter personality traits"
- "Compare the backgrounds of Harry and Ron" -> "Harry Ron background family"
- "How does the Sorting Hat work?" -> "Sorting Hat"
Keep ONLY the specific nouns, proper names, and domain terms that would appear in the text.
`
        : "";

    return `You are a query planning assistant for a RAG (Retrieval-Augmented Generation) system.
Your task is to review and improve a preliminary query plan created by a heuristic planner.

Use the following context to inform your sub-query decomposition and strategy selection:
${context}
${keywordGuidance}

User Query: "${query}"

Heuristic Plan (preliminary analysis):
${heuristicJSON}

Your job:
1. Review the heuristic plan above for correctness and completeness.
2. Improve sub-query decomposition if the heuristic missed nuances or opportunities.
3. Correct the complexity classification if it seems wrong.
4. Refine sub-query wording for better retrieval results.
5. Add or remove sub-queries as appropriate.

Guidelines:
- Simple queries (single concept): Use ONE sub-query
- Moderate queries (2-3 concepts): Break into 2-3 focused sub-queries
- Complex queries (comparisons, multi-part): Break into multiple (3-5) specific sub-queries
If the query asks about relationships between entities, dependencies, or connections, the 'graph' strategy would be effective.
If the query needs both relationship context and semantic similarity, 'graph_hybrid' combines both approaches.

Response Format: Provide an improved JSON object with this exact structure:
{
  "originalQuery": ${JSON.stringify(query)},
  "complexity": "simple" | "moderate" | "complex",
  "subQueries": [
    {
      "query": "sub-query text",
      "reasoning": "why this sub-query is needed",
      "topK": 10
    }
  ],
  "explanation": "brief explanation of the strategy"
}

Provide your improved plan as valid JSON:`;
  }

  private cleanComparisonConcept(value: string): string {
    return value
      .trim()
      .replace(/^[\s:;,.([\]"'`-]+/, "")
      .replace(/[\s:;,.)[\]"'`!?-]+$/, "")
      .trim();
  }

  private extractComparisonConcepts(query: string): [string, string] | null {
    const normalized = query.trim().replace(/[.!?\s]+$/, "");
    const patterns = [
      /\bdifference between\s+(.+?)\s+and\s+(.+)$/i,
      /\bcompare\s+(.+?)\s+to\s+(.+)$/i,
      /\bcompare\s+(.+?)\s+with\s+(.+)$/i,
      /\bcompare\s+(.+?)\s+and\s+(.+)$/i,
      /(.+?)\s+(?:vs\.?|versus)\s+(.+)$/i,
      /\bwhich is better:?\s+(.+?)\s+or\s+(.+)$/i,
    ] as const;

    for (const pattern of patterns) {
      const match = normalized.match(pattern);
      if (!match) {
        continue;
      }

      const left = this.cleanComparisonConcept(match[1]);
      const right = this.cleanComparisonConcept(match[2]);

      if (left && right) {
        return [left, right];
      }
    }

    return null;
  }

  /**
   * Analyze query complexity using lightweight NLP heuristics.
   * Returns a score from 0 (trivial) to 1 (very complex).
   */
  private analyzeComplexityScore(query: string, options: QueryPlannerOptions): number {
    let score = 0;
    const words = query.split(/\s+/).filter(Boolean);

    // Sentence / clause count
    const sentences = query.split(/[.!?;]+/).filter((s) => s.trim().length > 0);
    if (sentences.length >= 3) {
      score += 0.25;
    } else if (sentences.length === 2) {
      score += 0.15;
    }

    // Independent clauses separated by conjunctions
    const clauses = query.split(/\b(and|or|but|however|whereas|while)\b/i);
    if (clauses.length > 4) {
      score += 0.2;
    } else if (clauses.length > 2) {
      score += 0.1;
    }

    // Comparison / contrast indicators
    if (/\b(vs\.?|versus|compare|differ|between|better|worse|pros|cons)\b/i.test(query)) {
      score += 0.3;
    }

    // Multiple question words
    const questionWords = query.match(/\b(what|how|why|when|where|which|who)\b/gi) || [];
    if (questionWords.length >= 3) {
      score += 0.2;
    } else if (questionWords.length === 2) {
      score += 0.1;
    }

    // Word count factor
    if (words.length > 25) {
      score += 0.15;
    } else if (words.length > 15) {
      score += 0.05;
    }

    // Technical / domain indicators (code-like patterns)
    if (/[{}()[\]<>]|\w+\.\w+\(|=>|->/.test(query)) {
      score += 0.1;
    }

    // Context-aware boost: technical topics get a slight bump
    if (options.topicName || options.workspaceContext) {
      const ctx = `${options.topicName} ${options.workspaceContext}`.toLowerCase();
      const technicalTerms =
        /\b(api|code|deploy|server|database|algorithm|pipeline|config|docker|kubernetes|ci\/cd|testing)\b/i;
      score += technicalTerms.test(ctx) || technicalTerms.test(query) ? 0.1 : 0;
    }

    // Relationship / graph patterns
    const relationshipPatterns =
      /\b(relate[sd]?\s+to|connects?\s+(to|with)|depends?\s+on|linked\s+to|associated\s+with|interacts?\s+with|caused?\s+by|leads?\s+to|calls?|imports?|inherits?\s+from|extends?)\b/i;
    if (relationshipPatterns.test(query)) {
      score += 0.15;
    }

    return Math.min(score, 1);
  }

  /**
   * Create a query plan: heuristic first, then LLM refinement if available
   */
  public async createPlan(query: string, options: QueryPlannerOptions): Promise<QueryPlan> {
    this.logger.info("Creating query plan", {
      query: query.substring(0, 100),
      topicName: options.topicName,
    });

    // Early exit for trivial (empty / single-word) queries
    const trimmed = query.trim();
    if (trimmed.length === 0 || !trimmed.includes(" ")) {
      const reason = trimmed.length === 0 ? "empty query" : "single-word query";
      this.logger.debug("Trivial query detected, returning simple plan", { query: trimmed, reason });
      return {
        originalQuery: query,
        complexity: "simple",
        subQueries: [
          {
            query: trimmed || query,
            reasoning: "Direct search for trivial query",
            topK: options.topK,
          },
        ],
        explanation: "Trivial query handled with single search",
      };
    }

    // Check cache first
    const cacheKey = this.buildCacheKey(query, options);
    const cached = this.getCachedPlan(cacheKey);
    if (cached) {
      return cached;
    }

    // Step 1: Always start with heuristic planning
    const heuristicPlan = this.createHeuristicPlan(query, options);

    try {
      // Step 2: Try to refine with LLM, fall back to heuristic plan
      const plan = (await this.refinePlanWithLLM(query, heuristicPlan, options)) ?? heuristicPlan;
      const finalPlan = options.retrievalStrategy === RetrievalStrategy.BM25 ? this.convertPlanToKeywords(plan) : plan;

      this.cachePlan(cacheKey, finalPlan);
      return finalPlan;
    } catch (error) {
      this.logger.error("Failed to create query plan", {
        error: error instanceof Error ? error.message : String(error),
        query: query.substring(0, 100),
        stage: "createPlan",
      });

      return options.retrievalStrategy === RetrievalStrategy.BM25
        ? this.convertPlanToKeywords(heuristicPlan)
        : heuristicPlan;
    }
  }

  /**
   * Refine a heuristic plan using the LLM provider
   */
  private async refinePlanWithLLM(
    query: string,
    heuristicPlan: QueryPlan,
    options: QueryPlannerOptions,
  ): Promise<QueryPlan | null> {
    try {
      const model = await this.llmProvider.selectModel({ family: options.modelFamily });
      if (!model) {
        this.logger.debug("No language models available, using heuristic plan");
        return null;
      }

      // Build refinement prompt with heuristic plan
      const prompt = this.buildRefinementPrompt(
        query,
        this.buildContextString(options),
        heuristicPlan,
        options.retrievalStrategy,
      );

      // Send request to LLM with timeout and proper cancellation
      const messages = [{ role: "user" as const, content: prompt }];

      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), LLM_TIMEOUT_MS);

      // Forward caller's abort signal if provided
      const onAbort = () => controller.abort();
      options.signal?.addEventListener("abort", onAbort);

      let responseText = "";
      try {
        const response = await model.sendRequest(messages, controller.signal);
        // Collect response
        for await (const chunk of response) {
          responseText += chunk;
        }
      } finally {
        clearTimeout(timeout);
        options.signal?.removeEventListener("abort", onAbort);
      }

      this.logger.debug("LLM refinement response received", {
        responseLength: responseText.length,
        modelId: model.id,
        modelFamily: options.modelFamily,
      });

      // Parse JSON response
      // Extract JSON from markdown code blocks if present (handles varied whitespace/CRLF)
      const jsonMatch = responseText.match(/```(?:json)?\s*\n?([\s\S]*?)\n?\s*```/);
      const jsonText = jsonMatch ? jsonMatch[1] : responseText;
      let cleanedJson = jsonText.trim();
      try {
        JSON.parse(cleanedJson);
      } catch {
        const match = cleanedJson.match(/\{[\s\S]*\}/);
        if (!match) {
          throw new Error("No valid JSON object found in LLM response");
        }
        cleanedJson = match[0];
      }

      const parsedJSON = JSON.parse(cleanedJson);

      if (typeof parsedJSON !== "object" || parsedJSON === null) {
        this.logger.warn("LLM returned non-object JSON");
        return null;
      }

      const plan = QueryPlanSchema.parse(parsedJSON) as QueryPlan;
      // Strip _heuristicFallback — only internal code may set this
      plan._heuristicFallback = false;

      // Apply constraints
      if (plan.subQueries.length > PLANNER_DEFAULTS.maxSubQueries) {
        plan.subQueries = plan.subQueries.slice(0, PLANNER_DEFAULTS.maxSubQueries);
      }

      // Set default topK if not specified or less
      plan.subQueries.forEach((sq: SubQuery) => {
        if (sq.topK === undefined || sq.topK < options.topK) {
          sq.topK = options.topK;
        }
      });

      this.logger.info("LLM-refined query plan created", {
        complexity: plan.complexity,
        subQueryCount: plan.subQueries.length,
        heuristicComplexity: heuristicPlan.complexity,
        heuristicSubQueries: heuristicPlan.subQueries.length,
      });

      return plan;
    } catch (error) {
      this.logger.warn("LLM refinement failed, using heuristic plan", {
        error: error instanceof Error ? error.message : String(error),
        stage: "refinePlanWithLLM",
        query: query.substring(0, 100),
        modelFamily: options.modelFamily,
      });
      return null;
    }
  }

  /**
   * Create a plan using heuristic rules (no LLM required)
   */
  private createHeuristicPlan(query: string, options: QueryPlannerOptions): QueryPlan {
    this.logger.debug("Creating heuristic query plan", {
      query: query.substring(0, 100),
      topicName: options.topicName,
    });

    const defaultTopK = options.topK;

    // Use NLP-based complexity score alongside pattern checks
    const complexityScore = this.analyzeComplexityScore(query, options);
    this.logger.debug("Complexity score computed", { complexityScore });

    // Pattern-based indicators
    const hasComparison = /\b(vs|versus|compare|difference|between|better|worse)\b/i.test(query);
    const hasMultipleQuestions = (query.match(/\?/g) || []).length > 1;
    const hasMultipleConcepts = query.split(/\band\b|\bor\b/i).length > 2;
    const isLongQuery = query.split(/\s+/).length > 15;

    // Graph signal detection
    const hasRelationshipSignal =
      /\b(relate[sd]?\s+to|connects?|depends?\s+on|linked\s+to|associated\s+with|interacts?\s+with|calls?|imports?|inherits?|extends?)\b/i.test(
        query,
      );
    const hasHolisticSignal =
      /\b(main\s+themes?|overview|summarize|high[\s-]?level|big\s+picture|overall|key\s+concepts?)\b/i.test(query);

    let complexity: "simple" | "moderate" | "complex";
    let subQueries: SubQuery[];
    let explanation: string;

    if (hasComparison || complexityScore >= 0.6) {
      // Comparison or high-complexity query
      complexity = "complex";

      const comparisonConcepts = hasComparison ? this.extractComparisonConcepts(query) : null;

      if (comparisonConcepts) {
        // Clean structured extraction
        subQueries = [
          {
            query: comparisonConcepts[0],
            reasoning: `Search for information about ${comparisonConcepts[0]}`,
            topK: defaultTopK,
          },
          {
            query: comparisonConcepts[1],
            reasoning: `Search for information about ${comparisonConcepts[1]}`,
            topK: defaultTopK,
          },
        ];
      } else if (hasComparison) {
        // Fallback: split by comparison keywords and filter noise
        const parts = query.split(/\b(vs|versus|compare|difference|between)\b/i);
        subQueries = parts
          .filter((p) => p.trim().length > 3)
          .filter((p) => !/^(vs|versus|compare|difference|between|and)$/i.test(p.trim()))
          .map((part) => ({
            query: part.trim(),
            reasoning: `Search for information about ${part.trim()}`,
            topK: defaultTopK,
          }));
      } else {
        // High complexity but not a comparison — use hybrid strategy
        const parts = query.split(/[.!?;]\s+|\band\b|\bor\b/i);
        subQueries = parts
          .filter((p) => p.trim().length > 3)
          .map((part, _index) => ({
            query: part.trim(),
            reasoning: `Search for ${part.trim()}`,
            topK: defaultTopK,
          }));
      }

      explanation = hasComparison
        ? "Comparison query broken into parallel searches for each concept"
        : "Complex query decomposed with hybrid strategy";
    } else if (hasMultipleQuestions || hasMultipleConcepts || complexityScore >= 0.35) {
      // Multiple concepts - moderate complexity
      complexity = "moderate";

      // Split by common delimiters
      const parts = query.split(/[.!?;]\s+|\band\b/i);
      subQueries = parts
        .filter((p) => p.trim().length > 5)
        .slice(0, PLANNER_DEFAULTS.maxSubQueries)
        .map((part, _index) => ({
          query: part.trim(),
          reasoning: `Search for ${part.trim()}`,
          topK: defaultTopK,
        }));

      explanation = "Multi-concept query split into focused sub-searches";
    } else if (isLongQuery) {
      // Long query - extract key phrases
      complexity = "moderate";

      // Extract top keywords by filtering out stop words
      const keywords = extractKeywords(query, {
        sanitizeRegex: /[^a-zA-Z0-9]/g,
        replacement: "",
        deduplicate: false,
      });

      // Use the full query as primary, plus a keyword-focused sub-query if useful
      subQueries = [
        {
          query: query,
          reasoning: "Full query for comprehensive search",
          topK: defaultTopK,
        },
      ];

      if (keywords.length >= 3) {
        subQueries.push({
          query: keywords.slice(0, 6).join(" "),
          reasoning: "Keyword-focused search for key concepts",
          topK: defaultTopK,
        });
      }

      explanation = "Long query searched as-is with keyword-focused follow-up";
    } else {
      // Simple query - single sub-query
      complexity = "simple";

      subQueries = [
        {
          query: query,
          reasoning: "Direct search for the query",
          topK: defaultTopK,
        },
      ];

      explanation = "Simple, focused query requires single search";
    }

    // Ensure we have at least one sub-query
    if (subQueries.length === 0) {
      subQueries = [
        {
          query: query,
          reasoning: "Fallback to full query search",
          topK: defaultTopK,
        },
      ];
    }

    // Apply maxSubQueries constraint uniformly across all branches
    if (subQueries.length > PLANNER_DEFAULTS.maxSubQueries) {
      subQueries = subQueries.slice(0, PLANNER_DEFAULTS.maxSubQueries);
    }

    if (hasRelationshipSignal || hasHolisticSignal) {
      explanation += " Graph-aware retrieval recommended for this query.";
    }

    const plan: QueryPlan = {
      originalQuery: query,
      complexity,
      subQueries,
      explanation,
    };

    this.logger.info("Heuristic query plan created", {
      complexity: plan.complexity,
      subQueryCount: plan.subQueries.length,
      complexityScore,
    });

    return plan;
  }
}
