import * as fs from "node:fs";
import * as path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import esbuild from "esbuild";

const arguments_ = process.argv.slice(2);
if (arguments_.some((argument) => argument !== "--check") || arguments_.length > 1) {
  throw new Error(`build: unsupported arguments: ${arguments_.join(" ")}`);
}
const checkOnly = arguments_[0] === "--check";
const here = path.dirname(fileURLToPath(import.meta.url));
const html = fs.readFileSync(path.join(here, "index.html"), "utf8");
const css = fs.readFileSync(path.join(here, "styles.css"), "utf8");

// Bundle the TS app into a single inline module script.
const bundled = await esbuild.build({
  entryPoints: [path.join(here, "app.ts")],
  bundle: true,
  format: "esm",
  minify: true,
  write: false,
  target: ["es2022"],
  platform: "browser",
});
const script = bundled.outputFiles[0].text;

const composed = html.replace("/*__STYLES__*/", () => css).replace("/*__SCRIPT__*/", () => script);

// Keep the generated resource self-contained and fail fast if lifecycle wiring disappears.
if (/<script\s+[^>]*src\s*=/.test(composed)) {
  throw new Error("build: UI bundle must not contain any external <script src>");
}
if (!composed.includes("data-ragnarok-graph-app")) {
  throw new Error("build: UI bundle must contain the graph app marker");
}
if (composed.match(/data-ragnarok-graph-app/g)?.length !== 1) {
  throw new Error("build: UI bundle must contain exactly one graph app shell");
}
if (!composed.includes("ontoolresult")) {
  throw new Error("build: UI bundle must wire ontoolresult");
}
if (!composed.includes("<svg")) {
  throw new Error("build: UI bundle must contain an SVG");
}
for (const requiredId of ["loading", "error", "status", "reset-view"]) {
  if (!composed.includes(`id="${requiredId}"`)) {
    throw new Error(`build: UI bundle must contain #${requiredId}`);
  }
}

const outPath = path.join(here, "..", "graphAppBundle.ts");
const out =
  "// AUTO-GENERATED by src/ui/graphApp/build.mjs — do not edit by hand.\n" +
  "// prettier-ignore\n" +
  "export const GRAPH_APP_HTML = " +
  JSON.stringify(composed) +
  ";\n";
if (checkOnly) {
  const current = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : "";
  if (current !== out) {
    throw new Error("build: graphAppBundle.ts is out of date; run npm run build:ui");
  }
} else {
  fs.writeFileSync(outPath, out, "utf8");
}
